name: Deploy Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permissions on gradlew
        run: icacls gradlew /grant Everyone:F

      - name: Build Executable file
        run: .\gradlew.bat createExe

      - name: Prepare Release Assets
        shell: pwsh
        run: |
          if (-Not (Test-Path release)) { New-Item -ItemType Directory -Path release }
          Copy-Item build\libs\ps3rpc-1.0-SNAPSHOT.jar release\ps3rpc.jar -Force
          Move-Item build\launch4j\ps3rpc.exe release\ps3rpc.exe -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            release/ps3rpc.jar
            release/ps3rpc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}