name: Deploy Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permissions
        run: icacls gradlew /grant Everyone:F

      - name: Build ShadowJar
        run: .\gradlew.bat shadowJar

      - name: Install Launch4j via Chocolatey
        shell: pwsh
        run: |
          choco install launch4j --version=3.14.0 -y

      - name: Package EXE with Launch4j
        shell: cmd
        run: |
          "C:\Program Files (x86)\Launch4j\launch4jc.exe" launch4j.xml

      - name: Prepare Release Assets
        shell: pwsh
        run: |
          if (-Not (Test-Path release)) { New-Item -ItemType Directory -Path release }
          Move-Item build\libs\ps3rpc-1.0-SNAPSHOT.jar release\ps3rpc.jar
          Move-Item ps3rpc.exe release\ps3rpc.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            release/ps3rpc.jar
            release/ps3rpc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}